name: Publish to Pypi

on:
  workflow_dispatch:
  release:
    types: ["published"]

jobs:
  lint:
    name: "Package and Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test-requirements.txt') }}
      - name: Install dependenciesgit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r test-requirements.txt --upgrade --upgrade-strategy eager
          pip install setuptools wheel twine --upgrade --upgrade-strategy eager
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Deploy
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
